2019-07-02 18:45:25,166 - DEBUG - tty.usbmodem0006822145041: Writing: 105 bytearray(b'\x1d\xa6\xbf\xd4\xc7\x12\x939\x7fU\xf4\xc9\xce\xd1\x8a\xade\xea\x03\x0e\xbd \xd6w\xe4\xc1\xec5\x0b\xef\xb9\x11G\xec\xde*\xd7\xe6\x1e\xfb\xf0\x04\xaagw[u\xca\x8cVX\xd5\x846GX\xd8\xe38Q\x89\x92\xbc\x8bj\x107h0\x93\r\xe6\x8e9\x91(WIy\xac\xed\xb4\xf1\xd4\x03\xcdC\xe8\xb1=Ia9\xaa\t\xa4')
2019-07-02 18:45:25,167 - DEBUG - tty.usbmodem0006822145041: TX: 61691da6bfd4c71293397f55f4c9ced18aad65ea030ebd20d677e4c1ec350befb91147ecde2ad7e61efbf004aa67775b75ca8c5658d584364758d8e338518992bc8b6a10376830930de68e399128574979acedb4f1d403cd43e8b13d496139aa09a4
2019-07-02 18:45:25,177 - DEBUG - tty.usbmodem0006822145041: RX: 03845384
2019-07-02 18:45:25,177 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 83, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,178 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,178 - DEBUG - tty.usbmodem0006822145041: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-07-02 18:45:25,178 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,178 - DEBUG - tty.usbmodem0006822145041: TX: 059f01000100
2019-07-02 18:45:25,179 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,180 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,180 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,180 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,180 - DEBUG - tty.usbmodem0006822145041: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-07-02 18:45:25,180 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,187 - DEBUG - tty.usbmodem0006822145041: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-07-02 18:45:25,188 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,188 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,188 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,189 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,189 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-07-02 18:45:25,189 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,190 - DEBUG - tty.usbmodem0006822145041: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-07-02 18:45:25,190 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,191 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,191 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,191 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,191 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-07-02 18:45:25,192 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,192 - DEBUG - tty.usbmodem0006822145041: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-07-02 18:45:25,192 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,194 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,194 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,194 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,194 - DEBUG - tty.usbmodem0006822145041: Writing: 97 bytearray(b'')
2019-07-02 18:45:25,195 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,195 - DEBUG - tty.usbmodem0006822145041: TX: 0161
2019-07-02 18:45:25,195 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,196 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,197 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,198 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,198 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,198 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,205 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,205 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,206 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,206 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,206 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,207 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,207 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,208 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,208 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,209 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,209 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,209 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,209 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,210 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,210 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,210 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,210 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,210 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,211 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,211 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,212 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,212 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,212 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,213 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,214 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,220 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,220 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,221 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,221 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,221 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,222 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:25,223 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:25,223 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:25,223 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,224 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,224 - DEBUG - tty.usbmodem0006822145041: RX: 03849f00
2019-07-02 18:45:25,224 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 159, 'status': 0, 'data': bytearray(b'')}}
2019-07-02 18:45:25,224 - INFO - tty.usbmodem0006822145041: Success
2019-07-02 18:45:25,224 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,224 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,225 - DEBUG - tty.usbmodem0006822145041: RX: 058492000000
2019-07-02 18:45:25,225 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 146, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-02 18:45:25,225 - INFO - tty.usbmodem0006822145041: SubnetAdd: {'subnet_handle': 0}
2019-07-02 18:45:25,225 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,225 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,225 - DEBUG - tty.usbmodem0006822145041: RX: 058497000000
2019-07-02 18:45:25,226 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-02 18:45:25,226 - INFO - tty.usbmodem0006822145041: AppkeyAdd: {'appkey_handle': 0}
2019-07-02 18:45:25,226 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,226 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,226 - DEBUG - tty.usbmodem0006822145041: RX: 058497000100
2019-07-02 18:45:25,226 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x01\x00')}}
2019-07-02 18:45:25,227 - INFO - tty.usbmodem0006822145041: AppkeyAdd: {'appkey_handle': 1}
2019-07-02 18:45:25,227 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,228 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,229 - DEBUG - tty.usbmodem0006822145041: RX: 03846100
2019-07-02 18:45:25,229 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 97, 'status': 0, 'data': bytearray(b'')}}
2019-07-02 18:45:25,230 - INFO - tty.usbmodem0006822145041: Success
2019-07-02 18:45:25,230 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,231 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,262 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d30001c8639509c2c2
2019-07-02 18:45:25,264 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -45, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-02 18:45:25,264 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -45, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-02 18:45:25,264 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:25,264 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:25,265 - INFO - tty.usbmodem0006822145041: Received UUID 9db77a0526b8734988639509c242d107 with RSSI: -45 dB
2019-07-02 18:45:27,177 - DEBUG - tty.usbmodem0006822145041: Writing: 98 bytearray(b'')
2019-07-02 18:45:27,189 - DEBUG - tty.usbmodem0006822145041: TX: 0162
2019-07-02 18:45:27,212 - DEBUG - tty.usbmodem0006822145041: Writing: 99 bytearray(b'\x00\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00')
2019-07-02 18:45:27,218 - DEBUG - tty.usbmodem0006822145041: TX: 2d63009db77a0526b8734988639509c242d10718eed9c2a56add85049ffc3c59ad0e120000000000001000000000
2019-07-02 18:45:27,241 - DEBUG - tty.usbmodem0006822145041: RX: 03846200
2019-07-02 18:45:27,257 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 98, 'status': 0, 'data': bytearray(b'')}}
2019-07-02 18:45:27,270 - INFO - tty.usbmodem0006822145041: Success
2019-07-02 18:45:27,281 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:27,304 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:27,327 - DEBUG - tty.usbmodem0006822145041: RX: 0484630000
2019-07-02 18:45:27,339 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 99, 'status': 0, 'data': bytearray(b'\x00')}}
2019-07-02 18:45:27,351 - INFO - tty.usbmodem0006822145041: Provision: {'context': 0}
2019-07-02 18:45:27,362 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:27,387 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:27,409 - DEBUG - tty.usbmodem0006822145041: RX: 02c100
2019-07-02 18:45:27,415 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvLinkEstablished, data: {'context_id': 0}}
2019-07-02 18:45:27,427 - INFO - tty.usbmodem0006822145041: {event: ProvLinkEstablished, data: {'context_id': 0}}
2019-07-02 18:45:27,438 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:27,463 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:27,469 - INFO - tty.usbmodem0006822145041: Link established
2019-07-02 18:45:27,488 - DEBUG - tty.usbmodem0006822145041: RX: 0bc3000e0001000000000000
2019-07-02 18:45:27,488 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvCapsReceived, data: {'context_id': 0, 'num_elements': 14, 'public_key_type': 0, 'static_oob_types': 1, 'output_oob_size': 0, 'output_oob_actions': 0, 'input_oob_size': 0, 'input_oob_actions': 0}}
2019-07-02 18:45:27,488 - INFO - tty.usbmodem0006822145041: {event: ProvCapsReceived, data: {'context_id': 0, 'num_elements': 14, 'public_key_type': 0, 'static_oob_types': 1, 'output_oob_size': 0, 'output_oob_actions': 0, 'input_oob_size': 0, 'input_oob_actions': 0}}
2019-07-02 18:45:27,489 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:27,490 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:27,490 - INFO - tty.usbmodem0006822145041: Received capabilities
2019-07-02 18:45:27,491 - INFO - tty.usbmodem0006822145041: Number of elements: 14
2019-07-02 18:45:27,492 - DEBUG - tty.usbmodem0006822145041: Writing: 102 bytearray(b'\x00\x00\x00\x00')
2019-07-02 18:45:27,493 - DEBUG - tty.usbmodem0006822145041: TX: 056600000000
2019-07-02 18:45:27,500 - DEBUG - tty.usbmodem0006822145041: RX: 0484660000
2019-07-02 18:45:27,500 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 102, 'status': 0, 'data': bytearray(b'\x00')}}
2019-07-02 18:45:27,501 - INFO - tty.usbmodem0006822145041: OobUse: {'context': 0}
2019-07-02 18:45:27,501 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:27,501 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:27,665 - DEBUG - tty.usbmodem0006822145041: RX: 62c700b4be2d0e86075044fe9965558129d496dfaedb9cae87524e564a33aa5b3766d0edf4fb5dc8dba2d21ca06e28561a74aadaa07d9b436a35a1bd0a30df5beec12a2a10a72db801fe7fe471669467531262c946d4a7cb82a0d7d4a1d9be9b6d2592
2019-07-02 18:45:27,665 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvEcdhRequest, data: {'context_id': 0, 'peer_public': bytearray(b'\xb4\xbe-\x0e\x86\x07PD\xfe\x99eU\x81)\xd4\x96\xdf\xae\xdb\x9c\xae\x87RNVJ3\xaa[7f\xd0\xed\xf4\xfb]\xc8\xdb\xa2\xd2\x1c\xa0n(V\x1at\xaa\xda\xa0}\x9bCj5\xa1\xbd\n0\xdf[\xee\xc1*'), 'node_private': bytearray(b'*\x10\xa7-\xb8\x01\xfe\x7f\xe4qf\x94gS\x12b\xc9F\xd4\xa7\xcb\x82\xa0\xd7\xd4\xa1\xd9\xbe\x9bm%\x92')}}
2019-07-02 18:45:27,666 - INFO - tty.usbmodem0006822145041: {event: ProvEcdhRequest, data: {'context_id': 0, 'peer_public': bytearray(b'\xb4\xbe-\x0e\x86\x07PD\xfe\x99eU\x81)\xd4\x96\xdf\xae\xdb\x9c\xae\x87RNVJ3\xaa[7f\xd0\xed\xf4\xfb]\xc8\xdb\xa2\xd2\x1c\xa0n(V\x1at\xaa\xda\xa0}\x9bCj5\xa1\xbd\n0\xdf[\xee\xc1*'), 'node_private': bytearray(b'*\x10\xa7-\xb8\x01\xfe\x7f\xe4qf\x94gS\x12b\xc9F\xd4\xa7\xcb\x82\xa0\xd7\xd4\xa1\xd9\xbe\x9bm%\x92')}}
2019-07-02 18:45:27,666 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:27,666 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:27,666 - INFO - tty.usbmodem0006822145041: ECDH request received
2019-07-02 18:45:27,667 - DEBUG - tty.usbmodem0006822145041: Writing: 104 bytearray(b'\x00\x97\xbc\xe5\xf8\xc2V\xf9\xb4u587\x8b[ 2\xd58\x80\x81\r\xbf"\x07M\x91\x9b>\xf5Q\x01\x7f')
2019-07-02 18:45:27,668 - DEBUG - tty.usbmodem0006822145041: TX: 22680097bce5f8c256f9b4753538378b5b2032d53880810dbf22074d919b3ef551017f
2019-07-02 18:45:27,673 - DEBUG - tty.usbmodem0006822145041: RX: 0484680000
2019-07-02 18:45:27,673 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 104, 'status': 0, 'data': bytearray(b'\x00')}}
2019-07-02 18:45:27,673 - INFO - tty.usbmodem0006822145041: EcdhSecret: {'context': 0}
2019-07-02 18:45:27,674 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:27,674 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:30,022 - DEBUG - tty.usbmodem0006822145041: RX: 2cc50000000000000010000000e5316982439618a4f2861134579e243218eed9c2a56add85049ffc3c59ad0e12
2019-07-02 18:45:30,023 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvComplete, data: {'context_id': 0, 'iv_index': 0, 'net_key_index': 0, 'address': 16, 'iv_update_flag': 0, 'key_refresh_flag': 0, 'device_key': bytearray(b'\xe51i\x82C\x96\x18\xa4\xf2\x86\x114W\x9e$2'), 'net_key': bytearray(b'\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')}}
2019-07-02 18:45:30,023 - INFO - tty.usbmodem0006822145041: {event: ProvComplete, data: {'context_id': 0, 'iv_index': 0, 'net_key_index': 0, 'address': 16, 'iv_update_flag': 0, 'key_refresh_flag': 0, 'device_key': bytearray(b'\xe51i\x82C\x96\x18\xa4\xf2\x86\x114W\x9e$2'), 'net_key': bytearray(b'\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')}}
2019-07-02 18:45:30,023 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:30,024 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:30,025 - INFO - tty.usbmodem0006822145041: Provisioning complete
2019-07-02 18:45:30,025 - INFO - tty.usbmodem0006822145041: 	Address(es): 0x10-0x1d
2019-07-02 18:45:30,025 - INFO - tty.usbmodem0006822145041: 	Device key: e5316982439618a4f2861134579e2432
2019-07-02 18:45:30,025 - INFO - tty.usbmodem0006822145041: 	Network key: 18eed9c2a56add85049ffc3c59ad0e12
2019-07-02 18:45:30,025 - INFO - tty.usbmodem0006822145041: Adding device key to subnet 0
2019-07-02 18:45:30,025 - INFO - tty.usbmodem0006822145041: Adding publication address of root element
2019-07-02 18:45:30,025 - DEBUG - tty.usbmodem0006822145041: Writing: 156 bytearray(b'\x10\x00\x00\x00\xe51i\x82C\x96\x18\xa4\xf2\x86\x114W\x9e$2')
2019-07-02 18:45:30,026 - DEBUG - tty.usbmodem0006822145041: TX: 159c10000000e5316982439618a4f2861134579e2432
2019-07-02 18:45:30,028 - DEBUG - tty.usbmodem0006822145041: Writing: 164 bytearray(b'\x10\x00')
2019-07-02 18:45:30,028 - DEBUG - tty.usbmodem0006822145041: TX: 03a41000
2019-07-02 18:45:30,029 - DEBUG - tty.usbmodem0006822145041: RX: 05849c000800
2019-07-02 18:45:30,030 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 156, 'status': 0, 'data': bytearray(b'\x08\x00')}}
2019-07-02 18:45:30,030 - INFO - tty.usbmodem0006822145041: DevkeyAdd: {'devkey_handle': 8}
2019-07-02 18:45:30,030 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:30,030 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:30,030 - DEBUG - tty.usbmodem0006822145041: RX: 0584a4000000
2019-07-02 18:45:30,031 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 164, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-02 18:45:30,031 - INFO - tty.usbmodem0006822145041: AddrPublicationAdd: {'address_handle': 0}
2019-07-02 18:45:30,031 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:30,031 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:30,129 - DEBUG - tty.usbmodem0006822145041: RX: 03c20000
2019-07-02 18:45:30,130 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvLinkClosed, data: {'context_id': 0, 'close_reason': 0}}
2019-07-02 18:45:30,130 - INFO - tty.usbmodem0006822145041: {event: ProvLinkClosed, data: {'context_id': 0, 'close_reason': 0}}
2019-07-02 18:45:30,130 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x104901c88>>
2019-07-02 18:45:30,131 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcde == evt.Event.CMD_RSP:
NameError: name 'event_opcde' is not defined

2019-07-02 18:45:30,131 - INFO - tty.usbmodem0006822145041: Provisioning link closed
2019-07-02 18:45:39,254 - DEBUG - tty.usbmodem0006822145041: exited read event
2019-07-02 18:45:46,251 - DEBUG - tty.usbmodem0006822145041: Writing: 105 bytearray(b'!n\xc7\x11("\xd9\xc2\\\xbd\x16\xa8F7\xd3\xf7\x83\x8cn!}`\xccS\xedH\xbf2\x96P\xb8\xabgZ\xe9}\x81\xb1\xe6\x02p\xb8\xbdZ\x80\x01\xcc\xe9\xbe\x14\xd5\x96H\xed\xc61<K\xb6\x91c\xe1$&6\xdb&\x9dsN$J\xa9\x07:A=@\xd8Q\x0c\xbc\x81\xae\x1d\x8f\x87\x0c#\xa3\xf8\xc0\xda\xba\x01(')
2019-07-02 18:45:46,251 - DEBUG - tty.usbmodem0006822145041: TX: 6169216ec7112822d9c25cbd16a84637d3f7838c6e217d60cc53ed48bf329650b8ab675ae97d81b1e60270b8bd5a8001cce9be14d59648edc6313c4bb69163e1242636db269d734e244aa9073a413d40d8510cbc81ae1d8f870c23a3f8c0daba0128
2019-07-02 18:45:46,261 - DEBUG - tty.usbmodem0006822145041: RX: 03845384
2019-07-02 18:45:46,261 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 83, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,262 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,262 - DEBUG - tty.usbmodem0006822145041: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-07-02 18:45:46,262 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,262 - DEBUG - tty.usbmodem0006822145041: TX: 059f01000100
2019-07-02 18:45:46,264 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,264 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,264 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,264 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,264 - DEBUG - tty.usbmodem0006822145041: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-07-02 18:45:46,264 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,271 - DEBUG - tty.usbmodem0006822145041: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-07-02 18:45:46,271 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,272 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,272 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,272 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,272 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-07-02 18:45:46,273 - DEBUG - tty.usbmodem0006822145041: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-07-02 18:45:46,273 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,274 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,275 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,276 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,277 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,277 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-07-02 18:45:46,277 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,277 - DEBUG - tty.usbmodem0006822145041: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-07-02 18:45:46,277 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,278 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,278 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,278 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,278 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,278 - DEBUG - tty.usbmodem0006822145041: Writing: 97 bytearray(b'')
2019-07-02 18:45:46,279 - DEBUG - tty.usbmodem0006822145041: TX: 0161
2019-07-02 18:45:46,279 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,279 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,280 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,281 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,282 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,282 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,282 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,292 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,292 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,292 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,293 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,293 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,293 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,293 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,293 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,293 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,294 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,294 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,294 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,294 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,294 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,294 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,295 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,295 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,295 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,295 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,296 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,296 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,296 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,296 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,297 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,298 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,298 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,308 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,308 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,309 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,309 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:45:46,309 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:45:46,309 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:45:46,311 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,311 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,312 - DEBUG - tty.usbmodem0006822145041: RX: 03849f00
2019-07-02 18:45:46,312 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 159, 'status': 0, 'data': bytearray(b'')}}
2019-07-02 18:45:46,312 - INFO - tty.usbmodem0006822145041: Success
2019-07-02 18:45:46,312 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,313 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,313 - DEBUG - tty.usbmodem0006822145041: RX: 058492000000
2019-07-02 18:45:46,313 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 146, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-02 18:45:46,313 - INFO - tty.usbmodem0006822145041: SubnetAdd: {'subnet_handle': 0}
2019-07-02 18:45:46,314 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,314 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,322 - DEBUG - tty.usbmodem0006822145041: RX: 058497000000
2019-07-02 18:45:46,324 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-02 18:45:46,326 - INFO - tty.usbmodem0006822145041: AppkeyAdd: {'appkey_handle': 0}
2019-07-02 18:45:46,326 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,327 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,328 - DEBUG - tty.usbmodem0006822145041: RX: 058497000100
2019-07-02 18:45:46,329 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x01\x00')}}
2019-07-02 18:45:46,329 - INFO - tty.usbmodem0006822145041: AppkeyAdd: {'appkey_handle': 1}
2019-07-02 18:45:46,329 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,330 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:46,330 - DEBUG - tty.usbmodem0006822145041: RX: 03846100
2019-07-02 18:45:46,330 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 97, 'status': 0, 'data': bytearray(b'')}}
2019-07-02 18:45:46,330 - INFO - tty.usbmodem0006822145041: Success
2019-07-02 18:45:46,330 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:46,338 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:48,256 - DEBUG - tty.usbmodem0006822145041: Writing: 98 bytearray(b'')
2019-07-02 18:45:48,256 - DEBUG - tty.usbmodem0006822145041: TX: 0162
2019-07-02 18:45:48,258 - DEBUG - tty.usbmodem0006822145041: RX: 03846200
2019-07-02 18:45:48,258 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 98, 'status': 0, 'data': bytearray(b'')}}
2019-07-02 18:45:48,258 - INFO - tty.usbmodem0006822145041: Success
2019-07-02 18:45:48,259 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10e3c6978>>
2019-07-02 18:45:48,259 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 239, in __event_handler
    if event_opcode == evt.Event.CMD_RSP:
NameError: name 'event_opcode' is not defined

2019-07-02 18:45:58,792 - DEBUG - tty.usbmodem0006822145041: exited read event
