2019-07-02 18:46:11,016 - DEBUG - tty.usbmodem0006822145041: Writing: 105 bytearray(b"\r\xf2\x05\xb5\xaaCd^Q\xfbD\xd5N\x08\xa9\x117@\x14\x8c\xc9\xee\xbf\x99\xe6\xa3\x9b\x0b\xd1A\x9e\xf7\xb2\xe5\xa0$\xc7~Zk\x8b\x11O\xe6\xc9\x7f\xc5\x9f,\xe8Z \xab\x99{\x14iq\x0b)(1\xbd\xd8\n=\xe3)\xd4\xf5\x84\xe0T\xd2Ow2V\x13\xa1\xe6\x00\xd1\x15+\xaf\x96\'\x00n\x9b>\xe5\xd2\x87\xd7")
2019-07-02 18:46:11,016 - DEBUG - tty.usbmodem0006822145041: TX: 61690df205b5aa43645e51fb44d54e08a9113740148cc9eebf99e6a39b0bd1419ef7b2e5a024c77e5a6b8b114fe6c97fc59f2ce85a20ab997b1469710b292831bdd80a3de329d4f584e054d24f77325613a1e600d1152baf9627006e9b3ee5d287d7
2019-07-02 18:46:11,026 - DEBUG - tty.usbmodem0006822145041: RX: 03845384
2019-07-02 18:46:11,026 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 83, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,027 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,027 - DEBUG - tty.usbmodem0006822145041: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-07-02 18:46:11,027 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,027 - DEBUG - tty.usbmodem0006822145041: TX: 059f01000100
2019-07-02 18:46:11,029 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,029 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,029 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,029 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,030 - DEBUG - tty.usbmodem0006822145041: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-07-02 18:46:11,030 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,031 - DEBUG - tty.usbmodem0006822145041: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-07-02 18:46:11,032 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,032 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,032 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,032 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,033 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-07-02 18:46:11,033 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,033 - DEBUG - tty.usbmodem0006822145041: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-07-02 18:46:11,033 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,040 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,041 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,041 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,041 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,041 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-07-02 18:46:11,042 - DEBUG - tty.usbmodem0006822145041: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-07-02 18:46:11,043 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,043 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,043 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,045 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,045 - DEBUG - tty.usbmodem0006822145041: Writing: 97 bytearray(b'')
2019-07-02 18:46:11,045 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,046 - DEBUG - tty.usbmodem0006822145041: TX: 0161
2019-07-02 18:46:11,046 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,047 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,047 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,048 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,048 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,049 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,056 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,057 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,057 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,057 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,058 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,059 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,059 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,060 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,060 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,060 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,061 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,061 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,061 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,061 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,061 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,062 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,062 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,062 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,062 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,063 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,073 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,074 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,074 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,074 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,075 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,076 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,076 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,076 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,077 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,077 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,080 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-02 18:46:11,080 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-02 18:46:11,080 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-02 18:46:11,080 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,080 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,081 - DEBUG - tty.usbmodem0006822145041: RX: 03849f00
2019-07-02 18:46:11,081 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 159, 'status': 0, 'data': bytearray(b'')}}
2019-07-02 18:46:11,081 - INFO - tty.usbmodem0006822145041: Success
2019-07-02 18:46:11,081 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,081 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,082 - DEBUG - tty.usbmodem0006822145041: RX: 058492000000
2019-07-02 18:46:11,082 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 146, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-02 18:46:11,082 - INFO - tty.usbmodem0006822145041: SubnetAdd: {'subnet_handle': 0}
2019-07-02 18:46:11,082 - DEBUG - tty.usbmodem0006822145041: RX: 058497000000
2019-07-02 18:46:11,082 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-02 18:46:11,082 - INFO - tty.usbmodem0006822145041: AppkeyAdd: {'appkey_handle': 0}
2019-07-02 18:46:11,083 - DEBUG - tty.usbmodem0006822145041: RX: 058497000100
2019-07-02 18:46:11,083 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x01\x00')}}
2019-07-02 18:46:11,083 - INFO - tty.usbmodem0006822145041: AppkeyAdd: {'appkey_handle': 1}
2019-07-02 18:46:11,083 - DEBUG - tty.usbmodem0006822145041: RX: 03846100
2019-07-02 18:46:11,083 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 97, 'status': 0, 'data': bytearray(b'')}}
2019-07-02 18:46:11,083 - INFO - tty.usbmodem0006822145041: Success
2019-07-02 18:46:11,092 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:11,092 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:11,750 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d50001c8639509c2c2
2019-07-02 18:46:11,763 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -43, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-02 18:46:11,764 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -43, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-02 18:46:11,778 - INFO - tty.usbmodem0006822145041: Received UUID 9db77a0526b8734988639509c242d107 with RSSI: -43 dB
2019-07-02 18:46:13,026 - DEBUG - tty.usbmodem0006822145041: Writing: 98 bytearray(b'')
2019-07-02 18:46:13,039 - DEBUG - tty.usbmodem0006822145041: TX: 0162
2019-07-02 18:46:13,057 - DEBUG - tty.usbmodem0006822145041: Writing: 99 bytearray(b'\x00\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00')
2019-07-02 18:46:13,068 - DEBUG - tty.usbmodem0006822145041: TX: 2d63009db77a0526b8734988639509c242d10718eed9c2a56add85049ffc3c59ad0e120000000000001000000000
2019-07-02 18:46:13,102 - DEBUG - tty.usbmodem0006822145041: RX: 03846200
2019-07-02 18:46:13,114 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 98, 'status': 0, 'data': bytearray(b'')}}
2019-07-02 18:46:13,126 - INFO - tty.usbmodem0006822145041: Success
2019-07-02 18:46:13,137 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <interactive_pyaci.Manager object at 0x10a50f7f0>>
2019-07-02 18:46:13,166 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 240, in __event_handler
    message = access.AccessMessage(event)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 116, in __init__
    self.opcode_raw = opcode_from_message_get(event._data["data"])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 101, in opcode_from_message_get
    format_bits = (data[0] & Opcode.FORMAT_MASK)
IndexError: bytearray index out of range

2019-07-02 18:46:13,213 - DEBUG - tty.usbmodem0006822145041: RX: 0484630000
2019-07-02 18:46:13,224 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 99, 'status': 0, 'data': bytearray(b'\x00')}}
2019-07-02 18:46:13,235 - INFO - tty.usbmodem0006822145041: Provision: {'context': 0}
2019-07-02 18:46:13,276 - DEBUG - tty.usbmodem0006822145041: RX: 02c100
2019-07-02 18:46:13,282 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvLinkEstablished, data: {'context_id': 0}}
2019-07-02 18:46:13,294 - INFO - tty.usbmodem0006822145041: {event: ProvLinkEstablished, data: {'context_id': 0}}
2019-07-02 18:46:13,305 - INFO - tty.usbmodem0006822145041: Link established
2019-07-02 18:46:13,327 - DEBUG - tty.usbmodem0006822145041: RX: 0bc3000e0001000000000000
2019-07-02 18:46:13,327 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvCapsReceived, data: {'context_id': 0, 'num_elements': 14, 'public_key_type': 0, 'static_oob_types': 1, 'output_oob_size': 0, 'output_oob_actions': 0, 'input_oob_size': 0, 'input_oob_actions': 0}}
2019-07-02 18:46:13,328 - INFO - tty.usbmodem0006822145041: {event: ProvCapsReceived, data: {'context_id': 0, 'num_elements': 14, 'public_key_type': 0, 'static_oob_types': 1, 'output_oob_size': 0, 'output_oob_actions': 0, 'input_oob_size': 0, 'input_oob_actions': 0}}
2019-07-02 18:46:13,328 - INFO - tty.usbmodem0006822145041: Received capabilities
2019-07-02 18:46:13,332 - INFO - tty.usbmodem0006822145041: Number of elements: 14
2019-07-02 18:46:13,334 - DEBUG - tty.usbmodem0006822145041: Writing: 102 bytearray(b'\x00\x00\x00\x00')
2019-07-02 18:46:13,334 - DEBUG - tty.usbmodem0006822145041: TX: 056600000000
2019-07-02 18:46:13,341 - DEBUG - tty.usbmodem0006822145041: RX: 0484660000
2019-07-02 18:46:13,341 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 102, 'status': 0, 'data': bytearray(b'\x00')}}
2019-07-02 18:46:13,342 - INFO - tty.usbmodem0006822145041: OobUse: {'context': 0}
2019-07-02 18:46:13,528 - DEBUG - tty.usbmodem0006822145041: RX: 62c700a4422f8a9a21d6ee22c987871682aefc2dd38d592979a0292d8ef55b4778cd599642790038e8620fe16f92ef64573ba322da1b2d49ba4ee4d2952cefe2bb7e3699f05c576fe3f76b8f0314a782327610ec639bbf892574d204922d28354dbbd3
2019-07-02 18:46:13,529 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvEcdhRequest, data: {'context_id': 0, 'peer_public': bytearray(b'\xa4B/\x8a\x9a!\xd6\xee"\xc9\x87\x87\x16\x82\xae\xfc-\xd3\x8dY)y\xa0)-\x8e\xf5[Gx\xcdY\x96By\x008\xe8b\x0f\xe1o\x92\xefdW;\xa3"\xda\x1b-I\xbaN\xe4\xd2\x95,\xef\xe2\xbb~6'), 'node_private': bytearray(b'\x99\xf0\\Wo\xe3\xf7k\x8f\x03\x14\xa7\x822v\x10\xecc\x9b\xbf\x89%t\xd2\x04\x92-(5M\xbb\xd3')}}
2019-07-02 18:46:13,529 - INFO - tty.usbmodem0006822145041: {event: ProvEcdhRequest, data: {'context_id': 0, 'peer_public': bytearray(b'\xa4B/\x8a\x9a!\xd6\xee"\xc9\x87\x87\x16\x82\xae\xfc-\xd3\x8dY)y\xa0)-\x8e\xf5[Gx\xcdY\x96By\x008\xe8b\x0f\xe1o\x92\xefdW;\xa3"\xda\x1b-I\xbaN\xe4\xd2\x95,\xef\xe2\xbb~6'), 'node_private': bytearray(b'\x99\xf0\\Wo\xe3\xf7k\x8f\x03\x14\xa7\x822v\x10\xecc\x9b\xbf\x89%t\xd2\x04\x92-(5M\xbb\xd3')}}
2019-07-02 18:46:13,529 - INFO - tty.usbmodem0006822145041: ECDH request received
2019-07-02 18:46:13,530 - DEBUG - tty.usbmodem0006822145041: Writing: 104 bytearray(b"\x008\xa4!\x13s\xeb\xdd\x8c\x83\x84%\x05\x9a\xff\x11\x12`y\'\xfd\x05\xd6}\x9a\xd4\xbd}q\x95@u%")
2019-07-02 18:46:13,530 - DEBUG - tty.usbmodem0006822145041: TX: 22680038a4211373ebdd8c838425059aff1112607927fd05d67d9ad4bd7d7195407525
2019-07-02 18:46:13,536 - DEBUG - tty.usbmodem0006822145041: RX: 0484680000
2019-07-02 18:46:13,536 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 104, 'status': 0, 'data': bytearray(b'\x00')}}
2019-07-02 18:46:13,537 - INFO - tty.usbmodem0006822145041: EcdhSecret: {'context': 0}
2019-07-02 18:46:13,911 - DEBUG - tty.usbmodem0006822145041: RX: 2cc50000000000000010000000837012b53e42c9993d0b199e6deca08918eed9c2a56add85049ffc3c59ad0e12
2019-07-02 18:46:13,912 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvComplete, data: {'context_id': 0, 'iv_index': 0, 'net_key_index': 0, 'address': 16, 'iv_update_flag': 0, 'key_refresh_flag': 0, 'device_key': bytearray(b'\x83p\x12\xb5>B\xc9\x99=\x0b\x19\x9em\xec\xa0\x89'), 'net_key': bytearray(b'\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')}}
2019-07-02 18:46:13,912 - INFO - tty.usbmodem0006822145041: {event: ProvComplete, data: {'context_id': 0, 'iv_index': 0, 'net_key_index': 0, 'address': 16, 'iv_update_flag': 0, 'key_refresh_flag': 0, 'device_key': bytearray(b'\x83p\x12\xb5>B\xc9\x99=\x0b\x19\x9em\xec\xa0\x89'), 'net_key': bytearray(b'\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')}}
2019-07-02 18:46:13,912 - INFO - tty.usbmodem0006822145041: Provisioning complete
2019-07-02 18:46:13,912 - INFO - tty.usbmodem0006822145041: 	Address(es): 0x10-0x1d
2019-07-02 18:46:13,912 - INFO - tty.usbmodem0006822145041: 	Device key: 837012b53e42c9993d0b199e6deca089
2019-07-02 18:46:13,912 - INFO - tty.usbmodem0006822145041: 	Network key: 18eed9c2a56add85049ffc3c59ad0e12
2019-07-02 18:46:13,912 - INFO - tty.usbmodem0006822145041: Adding device key to subnet 0
2019-07-02 18:46:13,913 - INFO - tty.usbmodem0006822145041: Adding publication address of root element
2019-07-02 18:46:13,913 - DEBUG - tty.usbmodem0006822145041: Writing: 156 bytearray(b'\x10\x00\x00\x00\x83p\x12\xb5>B\xc9\x99=\x0b\x19\x9em\xec\xa0\x89')
2019-07-02 18:46:13,913 - DEBUG - tty.usbmodem0006822145041: TX: 159c10000000837012b53e42c9993d0b199e6deca089
2019-07-02 18:46:13,915 - DEBUG - tty.usbmodem0006822145041: Writing: 164 bytearray(b'\x10\x00')
2019-07-02 18:46:13,915 - DEBUG - tty.usbmodem0006822145041: TX: 03a41000
2019-07-02 18:46:13,917 - DEBUG - tty.usbmodem0006822145041: RX: 05849c000800
2019-07-02 18:46:13,917 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 156, 'status': 0, 'data': bytearray(b'\x08\x00')}}
2019-07-02 18:46:13,918 - INFO - tty.usbmodem0006822145041: DevkeyAdd: {'devkey_handle': 8}
2019-07-02 18:46:13,918 - DEBUG - tty.usbmodem0006822145041: RX: 0584a4000000
2019-07-02 18:46:13,918 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 164, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-02 18:46:13,925 - INFO - tty.usbmodem0006822145041: AddrPublicationAdd: {'address_handle': 0}
2019-07-02 18:46:14,021 - DEBUG - tty.usbmodem0006822145041: RX: 03c20000
2019-07-02 18:46:14,022 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvLinkClosed, data: {'context_id': 0, 'close_reason': 0}}
2019-07-02 18:46:14,022 - INFO - tty.usbmodem0006822145041: {event: ProvLinkClosed, data: {'context_id': 0, 'close_reason': 0}}
2019-07-02 18:46:14,022 - INFO - tty.usbmodem0006822145041: Provisioning link closed
2019-07-02 18:47:09,896 - DEBUG - tty.usbmodem0006822145041: exited read event
