2019-06-26 14:48:16,980 - DEBUG - tty.usbmodem0006822145041: Writing: 105 bytearray(b"\xab\x03\x80?]\xd7%<\x19{\x07\xa8\x00V\xa0.\x02\xb8\xc6Id\xd0H\xd7\x9e1\x1e\x18TrD\xa4,\xcc\x99<n-\xaf\xd2\xd4c\x919e|\xcaQ-\x7f4\xe7\'7[m\\\x0b\xc0\x8fN`ap\x0fJ5P\xf4\x08\xa6\x80H\xab\x81(\xf0Y\x95\xd3C\xd2\x16\x03\xf4*\x15b\xe6\x80\x0e\xeb\xa9\x1b\n\xc1")
2019-06-26 14:48:16,980 - DEBUG - tty.usbmodem0006822145041: TX: 6169ab03803f5dd7253c197b07a80056a02e02b8c64964d048d79e311e18547244a42ccc993c6e2dafd2d4639139657cca512d7f34e727375b6d5c0bc08f4e6061700f4a3550f408a68048ab8128f05995d343d21603f42a1562e6800eeba91b0ac1
2019-06-26 14:48:18,984 - INFO - tty.usbmodem0006822145041: cmd KeypairSet, timeout waiting for event
2019-06-26 14:48:18,985 - DEBUG - tty.usbmodem0006822145041: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-06-26 14:48:18,985 - DEBUG - tty.usbmodem0006822145041: TX: 059f01000100
2019-06-26 14:48:20,986 - INFO - tty.usbmodem0006822145041: cmd AddrLocalUnicastSet, timeout waiting for event
2019-06-26 14:48:20,986 - DEBUG - tty.usbmodem0006822145041: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-06-26 14:48:20,986 - DEBUG - tty.usbmodem0006822145041: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-06-26 14:48:22,106 - DEBUG - tty.usbmodem0006822145041: RX: 8453030003840084038400840384008403840084038400840384008403840084038400840384008403840084038400841ac09db77a0526b8734988639509c242d107c60001c8639509c2c203849f8e1ac09db77a0526b8734988639509c242d107c10001c8639509c2c2038492811ac09db77a0526b8734988639509c242d107c70001c863
2019-06-26 14:48:22,106 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 8453030003840084038400840384008403840084038400840384008403840084038400840384008403840084038400841ac09db77a0526b8734988639509c242d107c60001c8639509c2c203849f8e1ac09db77a0526b8734988639509c242d107c10001c8639509c2c2038492811ac09db77a0526b8734988639509c242d107c70001c863
2019-06-26 14:48:22,990 - INFO - tty.usbmodem0006822145041: cmd SubnetAdd, timeout waiting for event
2019-06-26 14:48:22,990 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-06-26 14:48:22,990 - DEBUG - tty.usbmodem0006822145041: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-06-26 14:48:24,992 - INFO - tty.usbmodem0006822145041: cmd AppkeyAdd, timeout waiting for event
2019-06-26 14:48:24,993 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-06-26 14:48:24,994 - DEBUG - tty.usbmodem0006822145041: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-06-26 14:48:27,000 - INFO - tty.usbmodem0006822145041: cmd AppkeyAdd, timeout waiting for event
2019-06-26 14:48:27,000 - DEBUG - tty.usbmodem0006822145041: Writing: 97 bytearray(b'')
2019-06-26 14:48:27,000 - DEBUG - tty.usbmodem0006822145041: TX: 0161
2019-06-26 14:48:29,005 - INFO - tty.usbmodem0006822145041: cmd ScanStart, timeout waiting for event
2019-06-26 14:48:32,143 - DEBUG - tty.usbmodem0006822145041: RX: 9509c2c2038497811ac09db77a0526b8734988639509c242d107c60001c8639509c2c2038497811ac09db77a0526b8734988639509c242d107c10001c8639509c2c2038461831ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2
2019-06-26 14:48:32,143 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 9509c2c2038497811ac09db77a0526b8734988639509c242d107c60001c8639509c2c2038497811ac09db77a0526b8734988639509c242d107c10001c8639509c2c2038461831ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2
2019-06-26 14:48:48,190 - DEBUG - tty.usbmodem0006822145041: RX: c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a
2019-06-26 14:48:48,192 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a
2019-06-26 14:48:48,194 - DEBUG - tty.usbmodem0006822145041: RX: 0526b8734988
2019-06-26 14:48:48,195 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 0526b8734988
2019-06-26 14:48:56,214 - DEBUG - tty.usbmodem0006822145041: RX: 639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09d
2019-06-26 14:48:56,215 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09d
2019-06-26 14:49:10,252 - DEBUG - tty.usbmodem0006822145041: RX: b77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509
2019-06-26 14:49:10,254 - ERROR - tty.usbmodem0006822145041: Unable to deserialize b77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509
2019-06-26 14:49:20,281 - DEBUG - tty.usbmodem0006822145041: RX: c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c28484030084840084038400840384840384008403840084000300840384008403840084038400840384008403849f8e1ac09db77a0526b8734988639509c242d107c20001c8639509c2c2038492811ac09db77a0526b8734988639509c242d107c00001c8639509c2c2038497811ac09db77a0526b8734988639509c242d107c50001c8639509c2c2038497811ac09db77a0526b8734988639509c242d107c20001c8639509c2
2019-06-26 14:49:20,286 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvLinkClosed, data: {'context_id': 26, 'close_reason': 192}}
2019-06-26 14:49:20,286 - INFO - tty.usbmodem0006822145041: Provisioning link closed
2019-06-26 14:49:36,313 - DEBUG - tty.usbmodem0006822145041: RX: c2038461831ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21a
2019-06-26 14:49:36,316 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c2038461831ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21a
2019-06-26 14:49:50,353 - DEBUG - tty.usbmodem0006822145041: RX: c09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a
2019-06-26 14:49:50,357 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a
2019-06-26 14:49:50,357 - DEBUG - tty.usbmodem0006822145041: RX: 0526b8734988
2019-06-26 14:49:50,357 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 0526b8734988
2019-06-26 14:49:58,372 - DEBUG - tty.usbmodem0006822145041: RX: 639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09d
2019-06-26 14:49:58,372 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09d
2019-06-26 14:50:10,392 - DEBUG - tty.usbmodem0006822145041: RX: b77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509
2019-06-26 14:50:10,392 - ERROR - tty.usbmodem0006822145041: Unable to deserialize b77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509
2019-06-26 14:50:26,442 - DEBUG - tty.usbmodem0006822145041: RX: c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107bf0001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db7
2019-06-26 14:50:26,442 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvLinkClosed, data: {'context_id': 26, 'close_reason': 192}}
2019-06-26 14:50:26,442 - INFO - tty.usbmodem0006822145041: Provisioning link closed
2019-06-26 14:50:34,459 - DEBUG - tty.usbmodem0006822145041: RX: 7a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c5
2019-06-26 14:50:34,459 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 7a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c5
2019-06-26 14:50:34,460 - DEBUG - tty.usbmodem0006822145041: RX: 00
2019-06-26 14:50:34,460 - ERROR - tty.usbmodem0006822145041: Invalid packet: bytearray(b'\x00')
2019-06-26 14:50:34,460 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:50:34,460 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:50:34,463 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:50:42,471 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:50:42,471 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:50:56,513 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c400
2019-06-26 14:50:56,513 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c400
2019-06-26 14:50:56,513 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:50:56,513 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:50:56,514 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:51:04,530 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:51:04,531 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:51:18,572 - DEBUG - tty.usbmodem0006822145041: RX: c242d107ca0001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c600
2019-06-26 14:51:18,573 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107ca0001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c600
2019-06-26 14:51:18,573 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:51:18,573 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:51:18,573 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:51:26,593 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:51:26,593 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:51:40,617 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:51:40,617 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:51:40,617 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:51:40,618 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:51:40,618 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:51:48,644 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:51:48,645 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:52:02,688 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c200
2019-06-26 14:52:02,688 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c200
2019-06-26 14:52:02,688 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:52:02,688 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:52:02,688 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:52:10,705 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:52:10,706 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:52:24,749 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c700
2019-06-26 14:52:24,749 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c700
2019-06-26 14:52:24,749 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:52:24,750 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:52:24,750 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:52:32,761 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:52:32,762 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:52:46,781 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c800
2019-06-26 14:52:46,781 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c800
2019-06-26 14:52:46,782 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:52:46,782 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:52:46,782 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:52:54,801 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:52:54,803 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:53:08,834 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c400
2019-06-26 14:53:08,834 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c400
2019-06-26 14:53:08,834 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:53:08,835 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:53:08,835 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:53:16,833 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:53:16,833 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:53:30,880 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c600
2019-06-26 14:53:30,881 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c600
2019-06-26 14:53:30,881 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:53:30,881 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:53:30,881 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:53:38,890 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:53:38,891 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:53:52,909 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c800
2019-06-26 14:53:52,909 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c800
2019-06-26 14:53:52,909 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:53:52,910 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:53:52,910 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:54:00,938 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:54:00,940 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:54:14,981 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:54:14,984 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:54:14,985 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:54:14,986 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:54:14,986 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:54:22,991 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:54:22,993 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:54:37,018 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c800
2019-06-26 14:54:37,018 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c800
2019-06-26 14:54:37,019 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:54:37,019 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:54:37,019 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:54:45,031 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:54:45,032 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:54:59,069 - DEBUG - tty.usbmodem0006822145041: RX: c242d107bf0001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c700
2019-06-26 14:54:59,070 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107bf0001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c700
2019-06-26 14:54:59,071 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:54:59,071 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:54:59,071 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:55:07,085 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:55:07,085 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:55:21,133 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:55:21,133 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:55:21,133 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:55:21,133 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:55:21,134 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:55:29,157 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:55:29,157 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:55:43,201 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c800
2019-06-26 14:55:43,202 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c800
2019-06-26 14:55:43,203 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:55:43,205 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:55:43,207 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:55:51,228 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:55:51,228 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:56:05,274 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:56:05,275 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:56:05,276 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:56:05,277 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:56:05,279 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:56:15,300 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:56:15,301 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:56:29,325 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c600
2019-06-26 14:56:29,326 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c600
2019-06-26 14:56:29,327 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:56:29,327 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:56:29,327 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:56:37,353 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:56:37,354 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:56:51,384 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c200
2019-06-26 14:56:51,384 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c200
2019-06-26 14:56:51,384 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:56:51,385 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:56:51,385 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:56:59,401 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:56:59,401 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:57:15,436 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:57:15,438 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:57:15,438 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:57:15,438 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:57:15,438 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:57:23,472 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107ca0001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:57:23,473 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107ca0001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:57:37,493 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107ca0001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c300
2019-06-26 14:57:37,493 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107ca0001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c300
2019-06-26 14:57:37,493 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:57:37,493 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:57:37,494 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:57:45,511 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:57:45,512 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:58:01,550 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:58:01,550 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 14:58:01,550 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:58:01,550 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:58:01,550 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:58:09,574 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:58:09,574 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:58:23,616 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c000
2019-06-26 14:58:23,616 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c000
2019-06-26 14:58:23,616 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:58:23,616 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:58:23,617 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:58:31,631 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:58:31,631 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:58:45,694 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107bf00
2019-06-26 14:58:45,699 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107bf00
2019-06-26 14:58:45,700 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:58:45,701 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:58:45,702 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:58:53,692 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107bd0001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:58:53,692 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107bd0001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:59:07,725 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107bf0001c8639509c2c21ac09db77a0526b8734988639509c242d107bd0001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c400
2019-06-26 14:59:07,725 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107bf0001c8639509c2c21ac09db77a0526b8734988639509c242d107bd0001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107c400
2019-06-26 14:59:07,725 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:59:07,725 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:59:07,726 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:59:17,763 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:59:17,769 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:59:31,791 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c700
2019-06-26 14:59:31,792 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c700
2019-06-26 14:59:31,793 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:59:31,794 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:59:31,796 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 14:59:39,794 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:59:39,794 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 14:59:53,827 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107bd0001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c600
2019-06-26 14:59:53,827 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509c242d107bd0001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c600
2019-06-26 14:59:53,827 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 14:59:53,827 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 14:59:53,828 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 15:00:03,863 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 15:00:03,864 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c10001c8639509c2c21ac09db77a0526b8734988639509c242d107c40001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 15:00:17,908 - DEBUG - tty.usbmodem0006822145041: RX: c242d107b90001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107bd0001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 15:00:17,908 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107b90001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c20001c8639509c2c21ac09db77a0526b8734988639509c242d107bd0001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c00001c8639509c2c21ac09db77a0526b8734988639509c242d107c500
2019-06-26 15:00:17,908 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 15:00:17,908 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 15:00:17,909 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 15:00:27,946 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107bd0001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 15:00:27,947 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107bd0001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 15:00:41,986 - DEBUG - tty.usbmodem0006822145041: RX: c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107ca0001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c900
2019-06-26 15:00:41,987 - ERROR - tty.usbmodem0006822145041: Unable to deserialize c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c60001c8639509c2c21ac09db77a0526b8734988639509c242d107c50001c8639509c2c21ac09db77a0526b8734988639509c242d107ca0001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509c242d107c70001c8639509c2c21ac09db77a0526b8734988639509c242d107c900
2019-06-26 15:00:41,987 - DEBUG - tty.usbmodem0006822145041: RX: 01c8
2019-06-26 15:00:41,987 - ERROR - tty.usbmodem0006822145041: Exception with packet 01c8
2019-06-26 15:00:41,988 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 171, in run
    parsed_packet = event_deserialize(pkt)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 793, in event_deserialize
    return EVENT_LUT[data[1]](data[2:])
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_evt.py", line 531, in __init__
    __data["context_id"], = struct.unpack("<B", raw_data[0:1])
struct.error: unpack requires a buffer of 1 bytes

2019-06-26 15:00:50,009 - DEBUG - tty.usbmodem0006822145041: RX: 639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509
2019-06-26 15:00:50,010 - ERROR - tty.usbmodem0006822145041: Unable to deserialize 639509c2c21ac09db77a0526b8734988639509c242d107c80001c8639509c2c21ac09db77a0526b8734988639509c242d107c30001c8639509c2c21ac09db77a0526b8734988639509c242d107c90001c8639509c2c21ac09db77a0526b8734988639509
