2019-07-11 11:23:32,710 - DEBUG: Writing: 105 bytearray(b"$\x83\x9d\x07\x8e\xa9\x16\x87!\x18o\xb5f\x9a\xfe\x8d\xbdBZ]\xe1\x9f\xbc\xb7\xa3,r<#\xe0\x82\x94\x92b(\xf1\xc7\xbf`f\x9c\x0e\xa6Sk\xe9f\xa9\x98%F.[\xa0\x19\nq\xafV\xad\x98\xd34\x9aZkm\xe3\xa8\xc5p\xb3;R\'\xaa\x8d\xab\x1e\xd1\xae\r\x15F\x0eh\xe6\x80\xd5\xc8XDrt\xb1\x11")
2019-07-11 11:23:32,711 - DEBUG: TX: 616924839d078ea9168721186fb5669afe8dbd425a5de19fbcb7a32c723c23e08294926228f1c7bf60669c0ea6536be966a99825462e5ba0190a71af56ad98d3349a5a6b6de3a8c570b33b5227aa8dab1ed1ae0d15460e68e680d5c858447274b111
2019-07-11 11:23:32,721 - DEBUG: RX: 03845384
2019-07-11 11:23:32,721 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 83, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,721 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,722 - DEBUG: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-07-11 11:23:32,722 - DEBUG: TX: 059f01000100
2019-07-11 11:23:32,722 - DEBUG: RX: 03840084
2019-07-11 11:23:32,722 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,723 - DEBUG: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-07-11 11:23:32,723 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,723 - DEBUG: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-07-11 11:23:32,723 - DEBUG: RX: 03840084
2019-07-11 11:23:32,724 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,724 - DEBUG: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-07-11 11:23:32,724 - DEBUG: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-07-11 11:23:32,724 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,724 - DEBUG: RX: 03840084
2019-07-11 11:23:32,724 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,725 - DEBUG: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-07-11 11:23:32,725 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,725 - DEBUG: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-07-11 11:23:32,725 - DEBUG: RX: 03840084
2019-07-11 11:23:32,725 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,725 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,726 - DEBUG: RX: 03840084
2019-07-11 11:23:32,726 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,726 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,726 - DEBUG: RX: 03840084
2019-07-11 11:23:32,727 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,727 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,727 - DEBUG: RX: 03840084
2019-07-11 11:23:32,727 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,727 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,728 - DEBUG: RX: 03840084
2019-07-11 11:23:32,728 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,730 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,730 - DEBUG: RX: 03840084
2019-07-11 11:23:32,731 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,731 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,731 - DEBUG: RX: 03840084
2019-07-11 11:23:32,732 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,732 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,732 - DEBUG: RX: 03840084
2019-07-11 11:23:32,732 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,733 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,733 - DEBUG: RX: 03840084
2019-07-11 11:23:32,733 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-11 11:23:32,733 - ERROR: None: ERROR_INVALID_LENGTH
2019-07-11 11:23:32,734 - DEBUG: RX: 03849f00
2019-07-11 11:23:32,734 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 159, 'status': 0, 'data': bytearray(b'')}}
2019-07-11 11:23:32,734 - INFO: Success
2019-07-11 11:23:32,734 - DEBUG: RX: 058492000000
2019-07-11 11:23:32,734 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 146, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-11 11:23:32,734 - INFO: SubnetAdd: {'subnet_handle': 0}
2019-07-11 11:23:32,735 - DEBUG: RX: 058497000000
2019-07-11 11:23:32,735 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-11 11:23:32,735 - INFO: AppkeyAdd: {'appkey_handle': 0}
2019-07-11 11:23:32,736 - DEBUG: RX: 058497000100
2019-07-11 11:23:32,736 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x01\x00')}}
2019-07-11 11:23:32,736 - INFO: AppkeyAdd: {'appkey_handle': 1}
2019-07-11 11:23:41,189 - INFO: Received from node-red: "{\"op\":\"ProvisionScanStart\",\"nodeMessageId\":0}"
2019-07-11 11:23:41,190 - DEBUG: Writing: 97 bytearray(b'')
2019-07-11 11:23:41,190 - INFO: Received from node-red: "{\"op\":\"GetProvisionedDevices\",\"nodeMessageId\":1}"
2019-07-11 11:23:41,190 - DEBUG: TX: 0161
2019-07-11 11:23:41,192 - DEBUG: RX: 03846100
2019-07-11 11:23:41,192 - DEBUG: parsed_packet {event: CmdRsp, data: {'opcode': 97, 'status': 0, 'data': bytearray(b'')}}
2019-07-11 11:23:41,192 - INFO: Success
2019-07-11 11:23:42,793 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d90001c8639509c2c2
2019-07-11 11:23:42,793 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:42,793 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:42,793 - INFO: Received UUID 9db77a0526b8734988639509c242d107 with RSSI: -39 dB
2019-07-11 11:23:42,812 - INFO: Received from node-red: ""
2019-07-11 11:23:44,795 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107da0001c8639509c2c2
2019-07-11 11:23:44,795 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -38, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:44,795 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -38, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:44,810 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:23:44,816 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:23:46,798 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d90001c8639509c2c2
2019-07-11 11:23:46,798 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:46,798 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:46,799 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:23:46,799 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:23:48,811 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d90001c8639509c2c2
2019-07-11 11:23:48,811 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:48,811 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:48,812 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:23:48,813 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:23:50,809 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107da0001c8639509c2c2
2019-07-11 11:23:50,809 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -38, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:50,809 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -38, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:50,810 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:23:50,810 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:23:52,819 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d70001c8639509c2c2
2019-07-11 11:23:52,820 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:52,820 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:52,822 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:23:52,822 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:23:54,821 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d70001c8639509c2c2
2019-07-11 11:23:54,821 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:54,821 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:54,822 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:23:54,823 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:23:56,823 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107da0001c8639509c2c2
2019-07-11 11:23:56,825 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -38, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:56,825 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -38, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:56,826 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:23:56,826 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:23:58,830 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d70001c8639509c2c2
2019-07-11 11:23:58,830 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:58,830 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:23:58,831 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:23:58,833 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:00,834 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d30001c8639509c2c2
2019-07-11 11:24:00,834 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -45, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:00,835 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -45, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:00,836 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:00,838 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:02,840 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d70001c8639509c2c2
2019-07-11 11:24:02,840 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:02,840 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:02,841 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:02,842 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:04,850 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d70001c8639509c2c2
2019-07-11 11:24:04,850 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:04,851 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:04,851 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:04,852 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:06,853 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d00001c8639509c2c2
2019-07-11 11:24:06,854 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -48, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:06,854 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -48, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:06,854 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:06,855 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:08,858 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107db0001c8639509c2c2
2019-07-11 11:24:08,859 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -37, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:08,859 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -37, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:08,859 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:08,860 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:10,867 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d70001c8639509c2c2
2019-07-11 11:24:10,868 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:10,868 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:10,868 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:10,869 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:12,873 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d00001c8639509c2c2
2019-07-11 11:24:12,873 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -48, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:12,873 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -48, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:12,873 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:12,874 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:14,874 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d70001c8639509c2c2
2019-07-11 11:24:14,875 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:14,875 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:14,875 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:14,876 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:16,880 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d70001c8639509c2c2
2019-07-11 11:24:16,880 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:16,880 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:16,880 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:16,881 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:18,885 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d00001c8639509c2c2
2019-07-11 11:24:18,885 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -48, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:18,885 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -48, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:18,886 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:18,886 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:20,893 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d00001c8639509c2c2
2019-07-11 11:24:20,893 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -48, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:20,893 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -48, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:20,894 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:20,894 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:22,899 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107d30001c8639509c2c2
2019-07-11 11:24:22,899 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -45, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:22,899 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -45, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:22,900 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:22,903 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:24,907 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107c70001c8639509c2c2
2019-07-11 11:24:24,907 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -57, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:24,907 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -57, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:24,908 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:24,908 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:28,914 - DEBUG: RX: 1ac09db77a0526b8734988639509c242d107c50001c8639509c2c2
2019-07-11 11:24:28,914 - DEBUG: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -59, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:28,914 - INFO: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -59, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-11 11:24:28,915 - ERROR: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x100c34198>>
2019-07-11 11:24:28,916 - ERROR: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 238, in __event_handler
    "rssi": rssi
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 535, in newUnProvisionedDevice
    self.process_stdout(op, data)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 339, in process_stdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

2019-07-11 11:24:29,866 - DEBUG: RX: 04810200fe
2019-07-11 11:24:29,869 - DEBUG: parsed_packet {event: DeviceStarted, data: {'operating_mode': 2, 'hw_error': 0, 'data_credit_available': 254}}
2019-07-11 11:24:29,869 - INFO: Device rebooted.
